# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
      OWNER: rizwanejaznisum
      REPO: test-repo
      URL: https://webhook.site/0358ecb3-1500-4d37-a439-93139f77c082

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://api.github.com/repos/${{env.OWNER}}/${{env.REPO}}/releases?per_page=2"
          method: "GET"
          customHeaders: '{"Authorization": "Basic cml6d2FuZWphem5pc3VtOm5pc3VtMTIz"}'

      # Runs a single command using the runners shell
      - name: Save Response
        id: saveResponse
        run: |
         tag1=`echo '${{ steps.myRequest.outputs.response }}' | jq '.[0].tag_name'`
         tag2=`echo '${{ steps.myRequest.outputs.response }}' | jq '.[1].tag_name'`
         echo "::set-output name=tag1::$tag1"
         echo "::set-output name=tag2::$tag2"
         
      - name: Run Cmd
        id: runCmd
        uses: actions/checkout@v2
      - run: |
          git fetch --unshallow --tags
          git fetch
          tag1=`echo ${{steps.saveResponse.outputs.tag1}}`
          tag2=`echo ${{steps.saveResponse.outputs.tag2}}`
          
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw/origin\/}
          VAR=`echo $branch | awk '{print $NF}'`
          
          result=`git log $tag2..$tag1 --reverse --merges --pretty=tformat:"{\"sha\": \"%h\", \"label\": \"%s\"},%n" $@`
          result=`echo $result | sed 's/.$//' | perl -pe 'BEGIN{print "["}; END{print "]\n"}' | perl -pe 's/},]/}]/'`
          result=`echo $result | perl -pe 'BEGIN{print "{\"owner\": \"${{env.OWNER}}\", \"repo\": \"${{env.REPO}}\", \"releaseTag\": \"replacetaghere\", \"branch\": \"replacebranchhere\", \"prDetails\":"}; END{print "}"}'`
          result=`echo ${result/replacetaghere/$tag1}`
          result=`echo ${result/replacebranchhere/$VAR}`
          withQ=`echo $result | sed -e s/\"/\\\\\"/g`
          withQ=`echo \"$withQ\"`
          echo withQ
          #httpResponse=$(curl -o - -XPOST '${{env.URL}}' -H 'Content-Type: application/json' -d "${withQ}")
          #echo $httpResponse > ./report.html
      #- uses: EndBug/add-and-commit@v7
        #with:
           #add: './report.html'
           #author_name: GitHub action
           #message: "[GitHub-Action] Added report in the Repo"
           
      
