# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
      OWNER: rizwanejaznisum
      REPO: test-repo

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://api.github.com/repos/${{env.OWNER}}/${{env.REPO}}/releases?per_page=2"
          method: "GET"
          customHeaders: '{"Authorization": "Basic cml6d2FuZWphem5pc3VtOm5pc3VtMTIz"}'

      # Runs a single command using the runners shell
      - name: Save Response
        id: saveResponse
        run: |
         tag1=`echo '${{ steps.myRequest.outputs.response }}' | jq '.[0].tag_name'`
         tag2=`echo '${{ steps.myRequest.outputs.response }}' | jq '.[1].tag_name'`
         echo "::set-output name=tag1::$tag1"
         echo "::set-output name=tag2::$tag2"
         
      - name: Run Cmd
        id: runCmd
        uses: actions/checkout@v2
      - run: |
          git fetch --unshallow --tags
          git fetch
          tag1=`echo ${{steps.saveResponse.outputs.tag1}}`
          tag2=`echo ${{steps.saveResponse.outputs.tag2}}`
          result=`git log 9.0..10.0 --reverse --merges --pretty=tformat:"{\"sha\": \"%h\", \"label\": \"%s\"},%n" $@ | perl -pe 'BEGIN{print "["}; END{print "]\n"}' | perl -pe 's/},]/}]/'`
          result=`echo $result | perl -pe 'BEGIN{print "{\"owner\": \"${{env.OWNER}}\", \"repo\": \"${{env.REPO}}\", \"prDetails\":"}; END{print "}"}'`
          withQuotes=`echo '$result'`
          curl -H "Content-Type: application/json" -d $withQuotes -XPOST "https://webhook.site/0358ecb3-1500-4d37-a439-93139f77c082"
          
      - name: Show Result
        run: echo "abc"
           
      
