name: test

on:
   workflow_dispatch:
     inputs:
       branch:
         required: true
       text:
         required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git pull
          git branch -r --contains tags/19.0 --sort=-committerdate
          
           
