name: test

on:
   workflow_dispatch:
     inputs:
       branch:
         required: true
       text:
         required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git fetch
          git pull
          echo "tags......."
          git branch -a --contains tags/20.0 --sort=-committerdate
          #git name-rev --name-only --exclude=tags/* 5c7172daf4b361b75220ee566a063c6a53d1a819
          
           
