name: webhook

on:
   workflow_dispatch:
     inputs:
       branch:
         required: true
       text:
         required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git pull
          existed_in_remote=$(git ls-remote --heads origin ${{ github.event.inputs.branch }})
          if [[ -z ${existed_in_remote} ]]; then
            echo 0
          else
            git fetch
            git checkout ${{ github.event.inputs.branch }}
            git pull
          fi
    
      - name: Create Report
        run: |
          echo "${{ github.event.inputs.text }}" > ./report2.html 
          
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if git diff-index --quiet HEAD --; then
            echo "No changes"
          else
            # Changes
          
            git add ./report2.html
            git commit -m "Add changes"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          
           
