name: webhook

on:
  repository_dispatch:
    types: do-something

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git pull
          git checkout -b ${{ github.event.client_payload.branch }}
          git push origin ${{ github.event.client_payload.branch }}
          git status
          git branch --set-upstream-to=origin/${{ github.event.client_payload.branch }} ${{ github.event.client_payload.branch }}
    
      - name: Create Report
        run: |
          echo "${{ github.event.client_payload.text }}" > ./report2.html 
          cat ./report2.html
        
      - name: github commit
        uses: EndBug/add-and-commit@v7
        with:
           add: './report2.html'
           author_name: GitHub action
           message: "[GitHub-Action] Added report in the Repo"
           push: false
           
      - name: github push
        uses: actions/checkout@v2
      - run: |
          git push
           
