name: webhook

on:
  repository_dispatch:
    types: do-something

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: github pull
        uses: actions/checkout@v2
      - run: |
          git checkout master
          git pull origin master
          git checkout -b ${{ github.event.client_payload.branch }}
          git push origin ${{ github.event.client_payload.branch }}
    
      - name: Create Report
        run: |
          echo "${{ github.event.client_payload.text }}" > ./report2.html 
          cat ./report2.html
        
      - name: github commit
        uses: EndBug/add-and-commit@v7
        with:
           add: './report2.html'
           author_name: GitHub action
           message: "[GitHub-Action] Added report in the Repo"
           branch: ${{ github.event.client_payload.branch }}
